# Generated by Django 3.0.7 on 2020-06-23 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='avatars/guest.png', upload_to='avatars/<django.db.models.query_utils.DeferredAttribute object at 0x0000017FA1C948B0>')),
                ('cover_image', models.ImageField(default='avatars/cover.png', upload_to='avatars/<django.db.models.query_utils.DeferredAttribute object at 0x0000017FA1C948B0>')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
